valor = int(input("Valor a ser sacado: "))
cem = int(valor/100)
valor = valor - (cem*100)
cinq = int(valor/50)
valor = valor - (cinq*50)
dez = int(valor/10)
valor = valor - (dez*10)
cinco = int(valor/5)
valor = valor - (cinco*5)
um = int(valor/1)
valor = valor - (um*1)
print(cem,"Notas de cem\n",cinq,"Notas de Cinquenta\n",dez,"Notas de Dez\n",cinco,"Notas de cinco\n",um,"Notas de um")
