nome = input("Digite seu nome: ")
cpf = input("Digite seu cpf: ")
rg = input("Digite seu rg: ")
data = input("Digite sua data de nascimento: ")
sexo = input("Digite seu Gênero: ")
peso = input("Digite seu peso: ")
sangue = input("Digite seu tipo sanguíneo: ")
renda = input("Digite sua renda estimada ")
endereco = input("Digite seu endereço: ")
telefone = input("Digite seu número telefonico: ")
cidade = input("Digite a cidade onde mora: ")
estado = input("Digite o estado onde mora: ")
print("Nome: ",nome,"\nCpf: ",cpf,"\nRg: ",rg,"\nData de nascimento: ",data,"\nSexo: ",sexo,"\nPeso: ",peso,"Kg","\nTipo sanguíneo: ",sangue,"\nRenda estimada: ",renda,"\nEndereço: ",endereco,"\nNúmero telefonico: ",telefone,"\nReside em: ",cidade,"\nNo estado de: ",estado)
